CREATE TABLE appointments
(
    appointment_id UUID NOT NULL,
    time_stamp     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    service_type   VARCHAR(255),
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id)
);

CREATE TABLE customer
(
    customer_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fist_name    VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    phone_number INTEGER                                 NOT NULL,
    email        VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE stylists
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stylist_id     BIGINT                                  NOT NULL,
    stylist_name   VARCHAR(255)                            NOT NULL,
    specilizations VARCHAR(255)                            NOT NULL,
    availability   VARCHAR(255)                            NOT NULL,
    style_image    VARCHAR(255)                            NOT NULL,
    stylists_id    UUID                                    NOT NULL,
    CONSTRAINT pk_stylists PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_phone_number UNIQUE (phone_number);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES stylists (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMER9XEZ7c FOREIGN KEY (customer_id) REFERENCES appointments (appointment_id);

ALTER TABLE stylists
    ADD CONSTRAINT FK_STYLISTS_ON_STYLISTS FOREIGN KEY (stylists_id) REFERENCES appointments (appointment_id);