CREATE SCHEMA IF NOT EXISTS elNinoSchema;
CREATE SEQUENCE IF NOT EXISTS customer_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE appointments
(
    appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_stamp     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    service_type   VARCHAR(255),
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id)
);

CREATE TABLE customer
(
    customer_id         BIGINT NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE stylists
(
    stylist_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stylist_name   VARCHAR(255)                            NOT NULL,
    specilizations VARCHAR(255)                            NOT NULL,
    availability   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_stylists PRIMARY KEY (stylist_id)
);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMER
    FOREIGN KEY (customer_id)
    REFERENCES appointments (appointment_id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMERFfCzzp
    FOREIGN KEY (customer_id)
    REFERENCES stylists (stylist_id);

ALTER TABLE stylists
    ADD CONSTRAINT FK_STYLISTS_ON_STYLISTS
    FOREIGN KEY (stylist_id)
    REFERENCES appointments (appointment_id);